spring:
  sql:
    init:
      mode: always
      data-locations: classpath:persistence/data-h2.sql
  datasource:
    url: "jdbc:h2:mem:demo"
    username: "sa"
    password: "password"
    driver-class-name: org.h2.Driver
  jpa:
    hibernate.ddl-auto: create-drop # this is default for all in mem DB
    database: H2
    database-platform: org.hibernate.dialect.H2Dialect
    defer-datasource-initialization: true
