demo.greeting: こんにちわ

quote:
  host: "http://api.quotable.io"
  path: "/quotes/random"

management:
  info:
    env:
      enabled: true
  server:
    port: 8088
  endpoints:
    web:
      base-path: /actuator
      exposure:
        include: info,health,metrics,prometheus
    jmx:
      exposure:
        exclude: beans
  endpoint:
    info:
      enabled: true
    health:
      enabled: true
      probes:
        enabled: true
        add-additional-paths: true
      show-details: always
    prometheus:
      enabled: true
    shutdown:
      enabled: true

logging:
  level:
    de.sopracss.demo.interceptor.de.sopracss.demo.interceptor.WebLoggingInterceptor: DEBUG
