application:
  title: Demo
  version: 1.0.0
  log:
    level:
      base: INFO

spring:
    application:
      name: demo

demo:
  greeting: Hallo
  user.file: "classpath:user/users.json"

springdoc:
  swagger-ui:
    enabled: false

logging:
  level:
    root: ${application.log.level.base} # Env var "APPLICATION_LOG_LEVEL_BASE=INFO"
    org.springframework.web: DEBUG
    de.sopracss.demo.interceptor.WebLoggingInterceptor: INFO