spring:
  sql:
    init:
      mode: always
      data-locations: classpath:persistence/data.sql
  datasource:
    url: "jdbc:postgresql://localhost:5432/demo"
    username: "test"
    password: "test"
    driver-class-name: org.postgresql.Driver
  jpa:
    hibernate.ddl-auto: create-drop
    database: POSTGRESQL
    defer-datasource-initialization: true
