application:
  title: Demo
  version: 1.0.0
  log:
    level:
      base: INFO

spring:
    application:
      name: demo
    batch:
      jdbc:
        initialize-schema: always
      job:
        enabled: false

demo:
  greeting: Hallo
  user.file: "classpath:user/users.json"

logging:
  level:
    root: ${application.log.level.base} # Env var "APPLICATION_LOG_LEVEL_BASE=INFO"
    org.springframework.web: DEBUG
    de.sopracss.demo.interceptor.WebLoggingInterceptor: INFO