version: "3.8"
services:
  postgres:
    image: postgres:17-alpine
    ports:
      - "5432:5432"
    environment:
      - POSTGRES_DB=demo
      - POSTGRES_USER=test
      - POSTGRES_PASSWORD=test
      - PGDATA=/var/lib/postgresql/data/postgres
    volumes:
      # mount a default config file into container to use it at startup
      - ./postgres.conf:/etc/postgresql/postgresql.conf
      # this causes the container to use a non-host volume for Database and initialize schema and data ONLY ONCE:
      # - :/var/lib/postgresql/data:rw
      # this causes the container to use a host mounted volume for Database and initialize schema and data ONLY ONCE:
      # - /var/lib/postgresql/data:/var/lib/postgresql/data:rw
    command: postgres -c config_file=/etc/postgresql/postgresql.conf
    restart: always
