
global:
  scrape_interval: 30s
  scrape_timeout: 30s
# A list of scrape configurations.
scrape_configs:
  # The job name assigned to scraped metrics by default.
  # add prometheus scraper config here
